import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


import Navbar from "@/components/navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Aayush Kurup',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-primary text-info font-mono">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
